# Generated by Django 5.1.3 on 2024-11-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='People',
        ),
    ]
